# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/run/numberOfThreads 1

# configure marley for supernova
/inputs/particle_type marley
/inputs/generator marley
/inputs/MARLEY_json ../cfg/config_Nakazato_No_Oscillations.js
/inputs/isotropic false
/inputs/override_vertex_position false
/inputs/vertex_x 1.15 m
/inputs/vertex_y 3.0 m
/inputs/vertex_z 1.8 m

# configure supernova timing
/supernova/timing/on  true
/inputs/input_file supernova_data_Nakazato.root
/supernova/timing/th2_name  h2d_Nakazato_No_Oscillations

# output path
/inputs/output_file ../output/Nakazato_1000_events.root

# initialize run
/run/initialize
/random/setSeeds 0 31

# Supernova configs
/supernova/Event_Cutoff 100 s

# limit radioactive decays 
#/grdm/nucleusLimits 1 35 1 17  # aMin aMax zMin zMax

# run
/run/beamOn 1000

